Implemented enum
yiisoft/yii2-gii pull request #434
Opened 2020-05-24 20:20 UTC by uldisn

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | no implemented

I don't know how to make a test. Implement method  getTableSchema() and somehow load table scheme with enum field.

2020-12-26 16:53 UTC, uldisn commented
> Thank you for putting effort in the improvement of the Yii framework.
> We have reviewed your pull request.
> 
> In order for the framework and your solution to remain stable in the future, we have a unit test requirement in place. Therefore we can only accept your pull request if it is covered by unit tests.
> 
> Could you add these please?
> 
> Thanks!
> 
> P.S. If you have any questions about the creation of unit tests? Don't hesitate to ask for support. [More information about unit tests](http://www.yiiframework.com/doc-2.0/guide-test-unit.html)
> 
> _This is an automated comment, triggered by adding the label `pr:request for unit tests`._



> Thank you for putting effort in the improvement of the Yii framework.
> We have reviewed your pull request.
> 
> In order for the framework and your solution to remain stable in the future, we have a unit test requirement in place. Therefore we can only accept your pull request if it is covered by unit tests.
> 
> Could you add these please?
> 
> Thanks!
> 
> P.S. If you have any questions about the creation of unit tests? Don't hesitate to ask for support. [More information about unit tests](http://www.yiiframework.com/doc-2.0/guide-test-unit.html)
> 
> _This is an automated comment, triggered by adding the label `pr:request for unit tests`._

Unit test done

2020-12-26 16:53 UTC, uldisn commented
Unit test done

2020-12-27 10:55 UTC, bizley commented on src/generators/model/Generator.php
> +            $enum_values = explode(',', substr($column->dbType, 4, strlen($column->dbType) - 1));
Why not use `ColumnSchema::$enumValues`?

2020-12-27 15:34 UTC, uldisn commented on src/generators/model/Generator.php
> +            $enum_values = explode(',', substr($column->dbType, 4, strlen($column->dbType) - 1));
Fixed

2020-12-28 10:26 UTC, bizley commented
I've got few concerns:
1. How this will work with MSSQL? IIRC ENUM dbType is recognized but enumValues are left empty.
2. Overall this needs some tests with real DB engines.
3. Are we cool with that much code being generated here?
4. What do you think about having these optional/configured?

2020-12-28 10:38 UTC, uldisn commented
> I've got few concerns:
> 
> 1. How this will work with MSSQL? IIRC ENUM dbType is recognized but enumValues are left empty.
This is a problem for MS SQL users
> 2. Overall this needs some tests with real DB engines.
On MySql and MariaDB enum use more two years
> 3. Are we cool with that much code being generated here?
If use enum, is very useful.  Code generate, if model has enums.  Setting like $model->setTypePublic() also would also be good
> 4. What do you think about having these optional/configured?
Actually gii model form is so big. No need.

2020-12-29 08:28 UTC, uldisn commented
> 1. How this will work with MSSQL? IIRC ENUM dbType is recognized but enumValues are left empty.

Please provide me MSSQL schema dump like https://github.com/yiisoft/yii2-gii/pull/434/files#diff-eef4be0410fa93517728588e0c838dd2f9afb86ff7148c7f7d7636de99df3b00R486

2021-03-30 02:39 UTC, WinterSilence commented on src/generators/model/Generator.php
> +        return stripos(strtoupper($column->dbType), 'ENUM') === 0;
useless `strtoupper()`, `@return bool`

2021-03-30 04:59 UTC, uldisn commented on src/generators/model/Generator.php
> +        return stripos(strtoupper($column->dbType), 'ENUM') === 0;
I did not understand

2021-03-30 06:15 UTC, WinterSilence commented on src/generators/model/Generator.php
> +        return stripos(strtoupper($column->dbType), 'ENUM') === 0;
1. stripos — Find the position of the first occurrence of a **case-insensitive** substring in a string
2. Wrong return type

2021-03-30 07:13 UTC, uldisn commented on src/generators/model/Generator.php
> +        return stripos(strtoupper($column->dbType), 'ENUM') === 0;
Its ok? https://github.com/d3yii2/yii2-gii/blob/master/src/generators/model/Generator.php#L1162

2021-03-30 07:17 UTC, WinterSilence commented on src/generators/model/Generator.php
> +     * @return string
`return stripos($column->dbType, 'ENUM') !== false;` but `@return string`

2021-03-30 07:20 UTC, WinterSilence commented on src/generators/model/Generator.php
> +        return stripos($column->dbType, 'ENUM') !== false;
`return stripos($column->dbType, 'ENUM') === 0;` is better

2021-03-30 07:21 UTC, uldisn commented on src/generators/model/Generator.php
> +        return stripos($column->dbType, 'ENUM') !== false;
is fixed

2021-03-30 16:25 UTC, uldisn commented on src/generators/model/Generator.php
> +     * @return string
> I've got few concerns:
> 
> 1. How this will work with MSSQL? IIRC ENUM dbType is recognized but enumValues are left empty.
> 2. Overall this needs some tests with real DB engines.
> 3. Are we cool with that much code being generated here?
> 4. What do you think about having these optional/configured?

@bizley, good PR still holding. Why?

2021-03-30 16:35 UTC, uldisn commented
@samdark! Actual PR still waiting. @bizley added additional strange requirements.  It work.

2021-03-30 23:27 UTC, WinterSilence commented on src/generators/model/Generator.php
> +        return stripos(strtoupper($column->dbType), 'ENUM') === 0;
~~~php
/**
 * Validate is ENUM column.
 *
 * @param ColumnSchema $column Column instance
 * @return bool
 */
protected function isEnum(ColumnSchema $column)
{
    return !empty($column->enumValues) || stripos($column->dbType, 'ENUM') === 0;
}
~~~

2021-03-31 01:38 UTC, WinterSilence commented
@bizley

> How this will work with MSSQL? IIRC ENUM dbType is recognized but enumValues are left empty.

MSSQL don't have enum/set types

2021-03-31 05:14 UTC, uldisn commented on src/generators/model/Generator.php
> +        return stripos(strtoupper($column->dbType), 'ENUM') === 0;
fixed

2021-03-31 09:22 UTC, bizley commented
What do you mean by "strange"? These are legitimate concerns. You are just adding the feature but we will have to maintain it later on - I would like to at least be sure it works in most of the cases. And I'm not at the moment. I would like to see it tested with PostgreSQL since there is schema already in the tests added. And still no one said anything about the amount of additional code generated here (that is apart from you two guys, it's nice that you support each other like that).

2021-03-31 10:05 UTC, bizley requested changes

2021-03-31 10:05 UTC, bizley commented on src/generators/model/default/model.php
> +        foreach ($column_data['values'] as $enum_value){
```suggestion
        foreach ($column_data['values'] as $enum_value) {
```

2021-03-31 10:05 UTC, bizley commented on src/generators/model/default/model.php
> +    */
```suggestion
     * @return bool
     */
```

2021-03-31 10:05 UTC, bizley commented on src/generators/model/default/model.php
> +    public function <?=$column_data['isFunctionPrefix'].$enum_value['isFunctionSuffix']?>()
```suggestion
    public function <?= $column_data['isFunctionPrefix'] . $enum_value['isFunctionSuffix'] ?>()
```

2021-03-31 10:05 UTC, bizley commented on src/generators/model/default/model.php
> +        return $this-><?=$column_name?> === self::<?=$enum_value['const_name']?>;
```suggestion
        return $this-><?= $column_name ?> === self::<?= $enum_value['const_name'] ?>;
```

2021-03-31 10:05 UTC, bizley commented on src/generators/model/default/model.php
> +
Please remove empty line.

2021-03-31 10:05 UTC, bizley commented on tests/generators/ModelGeneratorTest.php
> +
Please remove empty line.

2021-03-31 10:05 UTC, bizley commented on tests/generators/ModelGeneratorTest.php
> +        $classCode = str_replace('<?php','',$codeFile);
```suggestion
        $classCode = str_replace('<?php', '', $codeFile);
```

2021-03-31 10:05 UTC, bizley commented on tests/generators/ModelGeneratorTest.php
> +        $classCode = str_replace('namespace app\models;','',$classCode);
```suggestion
        $classCode = str_replace('namespace app\models;', '', $classCode);
```

2021-03-31 10:05 UTC, bizley commented on tests/generators/ModelGeneratorTest.php
> +        $classCode = str_replace('use Yii;','',$classCode);
```suggestion
        $classCode = str_replace('use Yii;', '', $classCode);
```

2021-03-31 10:05 UTC, bizley commented on tests/generators/ModelGeneratorTest.php
> +        if(!class_exists('TestEnumModel')) {
```suggestion
        if (!class_exists('TestEnumModel')) {
```

2021-03-31 10:05 UTC, bizley commented on tests/generators/ModelGeneratorTest.php
> +            eval($classCode);
What is the reason behind this? Please remove commented out code.

2021-03-31 10:05 UTC, bizley commented on tests/generators/ModelGeneratorTest.php
> +
Please remove empty line.

2021-03-31 22:05 UTC, samdark commented on src/generators/model/default/model.php
> +if(!empty($enum)){
We usually use `<?php if (bla-bla): ?> content <?php endif ?>` in templates.

2021-03-31 22:05 UTC, samdark commented on tests/generators/ModelGeneratorTest.php
> +         * add method getTableSchema for seting test schema
```suggestion
         * Add method getTableSchema for setting test schema
```

2021-04-01 06:27 UTC, uldisn commented on tests/generators/ModelGeneratorTest.php
> +         * add method getTableSchema for seting test schema
Thank you. I probably fix everything.

2021-04-01 06:33 UTC, samdark commented on tests/generators/ModelGeneratorTest.php
> +            eval($classCode);
So why doing eval? @uldisn is it possible to avoid it?

2021-04-01 06:52 UTC, uldisn commented on tests/generators/ModelGeneratorTest.php
> +            eval($classCode);
I didn't find another way to run the generated class. How remember, problem is with namespaces.

2021-04-01 07:22 UTC, samdark commented on src/generators/model/default/model.php
> +    ?>
```suggestion
<?php foreach ($enum as $columnName => $columnData): ?>
```

2021-04-01 07:22 UTC, samdark commented on src/generators/model/default/model.php
> +    ?>
It's better to use this style in templates. Way more readable about what's nested where.

2021-04-01 08:00 UTC, uldisn commented on src/generators/model/default/model.php
> +    ?>
Fixed

2021-04-05 10:03 UTC, bizley requested changes

2021-04-05 10:03 UTC, bizley commented on src/generators/model/Generator.php
> +            $enum[$column->name]['func_opts_name'] = 'opts' . $columnCamelName;
Could we also have all array keys changed to pascalCase? To not have them mixed.

2021-04-06 09:02 UTC, bizley requested changes

2021-04-06 09:02 UTC, bizley commented on src/generators/model/Generator.php
> +            $rules['enum-' . $fieldName] = "['" . $fieldName . "', 'in', 'range' => array_keys(self::".$colummEnum['funcOptsName']."())]";
```suggestion
            $rules['enum-' . $fieldName] = "['" . $fieldName . "', 'in', 'range' => array_keys(self::" . $colummEnum['funcOptsName'] . '())]';
```

2021-04-06 09:02 UTC, bizley commented on src/generators/model/Generator.php
> +                    'functionSuffix' => Inflector::id2camel( Inflector::slug( $value))
```suggestion
                    'functionSuffix' => Inflector::id2camel(Inflector::slug($value))
```

2021-04-06 09:02 UTC, bizley commented on src/generators/model/default/model.php
> +<?php if (!empty($enum)):?>
```suggestion
<?php if (!empty($enum)): ?>
```

2021-04-06 09:25 UTC, uldisn commented on src/generators/model/Generator.php
> +            $rules['enum-' . $fieldName] = "['" . $fieldName . "', 'in', 'range' => array_keys(self::".$colummEnum['funcOptsName']."())]";
Done

2021-04-06 09:35 UTC, bizley commented on src/generators/model/Generator.php
> +            $rules['enum-' . $fieldName] = "['" . $fieldName . "', 'in', 'range' => array_keys(self::" . $colummEnum['funcOptsName'] . '())]';
```suggestion
        foreach ($columnsEnum as $fieldName => $columnEnum) {
            $rules['enum-' . $fieldName] = "['" . $fieldName . "', 'in', 'range' => array_keys(self::" . $columnEnum['funcOptsName'] . '())]';
```

2021-04-06 09:41 UTC, bizley approved these changes

2023-10-31 19:36 UTC, uldisn commented
I woke up

2023-11-28 12:39 UTC, thiagotalma commented
Apparently he went back to sleep.

@samdark, what do you think about removing this PR from the 2.2.7 milestone and releasing the version?

2023-11-28 15:42 UTC, uldisn commented
> Apparently he went back to sleep.

I define this initiative as illegal

2023-11-28 17:15 UTC, thiagotalma commented
> I define this initiative as illegal

I prefer to believe that this was some kind of slang, as I don't understand English well.

But if you were bothered by my joke, I apologize.

My intention was just to clear the milestone so that a new version can be released.

2023-11-28 17:25 UTC, uldisn commented
> I prefer to believe that this was some kind of slang, as I don't understand English well.
> 
> But if you were bothered by my joke, I apologize.
> 
> My intention was just to clear the milestone so that a new version can be released.



> > I define this initiative as illegal
> 
> I prefer to believe that this was some kind of slang, as I don't understand English well.
> 
> But if you were bothered by my joke, I apologize.
> 
> My intention was just to clear the milestone so that a new version can be released.



> > I define this initiative as illegal
> 
> I prefer to believe that this was some kind of slang, as I don't understand English well.
> 
> But if you were bothered by my joke, I apologize.
> 
> My intention was just to clear the milestone so that a new version can be released.



> > I define this initiative as illegal
> 
> I prefer to believe that this was some kind of slang, as I don't understand English well.
> 
> But if you were bothered by my joke, I apologize.
> 
> My intention was just to clear the milestone so that a new version can be released.

Don't take it seriously. When should I wake up?

2024-01-29 18:31 UTC, samdark approved these changes

2024-01-29 18:31 UTC, samdark commented
@uldisn time to wake up. Please add a line for CHANGELOG. Then I'll merge it.

2024-01-29 18:46 UTC, uldisn commented
> @uldisn time to wake up. Please add a line for CHANGELOG. Then I'll merge it.

Done!
Good night!

2024-02-01 09:00 UTC, merged

2024-02-01 09:00 UTC, samdark commented
Thank you!