Update Generator.php
yiisoft/yii2-gii pull request #444
Opened 2021-03-24 04:20 UTC by WinterSilence

Update preserved keywords

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes

2021-03-24 08:55 UTC, samdark approved these changes
Looks good. Please add a line for CHANGELOG.md. Thanks.

2021-03-24 09:20 UTC, WinterSilence commented
@samdark #445

2021-03-24 10:50 UTC, samdark commented
Please push to the same branch as in this PR. No need for separate PR.

2021-03-29 18:13 UTC, bizley requested changes

2021-03-29 18:13 UTC, bizley commented on CHANGELOG.md
> +- Chg #444: update preserved keywords in generator (WinterSilence)
```suggestion
- Enh #444: Updated reserved keywords in generator (WinterSilence)
```

2021-03-29 18:50 UTC, samdark approved these changes

2021-03-29 18:51 UTC, merged

2021-03-29 18:51 UTC, samdark commented
👍