Update crud controller view
yiisoft/yii2-gii pull request #450
Opened 2021-04-06 10:07 UTC by WinterSilence

1. merge model behaviors with `parent::behaviors()`
2. replace `Yii::$app->request` to `$this->request`
3. fast check `$this->request->isPost` before load & save model
4. add commented example of pagination and sorting settings for `ActiveDataProvider`

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  |

2021-04-06 10:13 UTC, bizley commented on src/generators/crud/default/controller.php
> +        return array_merge(
What is the use case behind this?

2021-04-06 10:14 UTC, bizley commented on src/generators/crud/default/controller.php
> +        $dataProvider = $searchModel->search($this->request->getQueryParams());
That property exists since Yii 2.0.36, before that version user will get an error.

2021-04-06 10:48 UTC, WinterSilence commented on src/generators/crud/default/controller.php
> +        return array_merge(
@bizley `baseControllerClass`:

~~~php
<?php

namespace app\controllers;

abstract class BackendController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::class,
                'rules' => [[
                    'allow' => true,
                    'roles' => ['@'],
                ]],
            ],
        ];
    }
}
~~~

2021-04-06 10:50 UTC, WinterSilence commented on src/generators/crud/default/controller.php
> +        $dataProvider = $searchModel->search($this->request->getQueryParams());
@bizley https://github.com/yiisoft/yii2-gii/blob/e11fec612df24f7d7223f133c23016003cae6987/composer.json#L26

2021-04-06 10:58 UTC, bizley commented on src/generators/crud/default/controller.php
> +        return array_merge(
So you want to change the vendor default to suit your own implementation? `yii\web\Controller` does not contain behaviors config. I'm not sure if adding that merge (while not being wrong per se) is fine but I would like to hear other opinions.

2021-04-06 10:59 UTC, bizley commented on src/generators/crud/default/controller.php
> +        $dataProvider = $searchModel->search($this->request->getQueryParams());
Yes, so anyone running Gii on Yii 2.0.14 to 2.0.35 will get an error - what is your point?

2021-04-06 11:16 UTC, WinterSilence commented on src/generators/crud/default/controller.php
> +        return array_merge(
@bizley it's only example, current code ignore/remove `baseControllerClass::behaviors()`

2021-04-06 11:22 UTC, WinterSilence commented on src/generators/crud/default/controller.php
> +        $dataProvider = $searchModel->search($this->request->getQueryParams());
@bizley don't understand you, `getQueryParams()`  exists in [2.0.14](https://github.com/yiisoft/yii2/blob/2.0.14/framework/web/Request.php#L625) - [2.0.35](https://github.com/yiisoft/yii2/blob/2.0.34/framework/web/Request.php#L653)

2021-04-06 11:23 UTC, samdark commented on src/generators/crud/default/controller.php
> +        $dataProvider = $searchModel->search($this->request->getQueryParams());
Then it's alright: https://github.com/yiisoft/yii2-gii/blob/master/composer.json#L26

2021-04-06 11:24 UTC, samdark commented on src/generators/crud/default/controller.php
> +        return array_merge(
Current code doesn't extend from any base controller.

2021-04-06 11:25 UTC, bizley commented on src/generators/crud/default/controller.php
> +        return array_merge(
`Generator::$baseControllerClass` is `yii\web\Controller`. If you change it in the config, Gii is not checking new controller's code to make amendments.

2021-04-06 11:30 UTC, WinterSilence commented on src/generators/crud/default/controller.php
> +        return array_merge(
@bizley you can set **any** parent controller

part of `@app/config/web.php`:
~~~
  $config['bootstrap'][] = 'gii';
  $config['modules']['gii'] = [
      'class' => 'yii\gii\Module',
      'generators' => [
          'crud' => [
              'class' => 'app\gii\generators\crud\Generator',
              'modelClass' => 'app\\models\\',
              'enablePjax' => true,
              'baseControllerClass' => 'app\controllers\BackendController', // replace `yii\web\Controller`
              'viewPath' => '@app/views/backend/',
              'templates' => [
                  'app' => '@app/gii/generators/crud/app',
              ]
          ],
      ],
  ];
~~~

2021-04-06 11:36 UTC, WinterSilence commented on src/generators/crud/default/controller.php
> +        return array_merge(
@bizley hmm... why it's work in my app?
![изображение](https://user-images.githubusercontent.com/3521094/113704804-4d179380-96e5-11eb-8d7a-e6c95dc7a0e0.png)

2021-04-06 11:46 UTC, bizley commented on src/generators/crud/default/controller.php
> +        return array_merge(
Yes, you can set any controller. That is the point of what I'm saying here. If in the base controller you chose, you throw exception in the `behaviors()` method, should Gii generate code not only merging `parent::behaviors()` but also using try/catch? Do you understand what I'm saying because we need to be on the same page here, otherwise the discussion is pointless.

2021-04-06 12:12 UTC, WinterSilence commented on src/generators/crud/default/controller.php
> +        return array_merge(
@bizley if user don't catch exception in `parent::behaviors()` then it's must be throwing in generated controllers too, it's better than erase user's code.

2021-04-06 15:12 UTC, samdark approved these changes
Looks alright overall. Please add a CHANGELOG.md line.

2021-04-06 15:12 UTC, samdark commented on src/generators/crud/default/controller.php
> +                    <?= "'$pk' => SORT_DESC,\n" ?>
Why DESC is default here? Just a template?

2021-04-06 15:43 UTC, bizley requested changes

2021-04-06 17:15 UTC, WinterSilence commented on src/generators/crud/default/controller.php
> +                    <?= "'$pk' => SORT_DESC,\n" ?>
@samdark yes, just example/template

2021-04-06 17:19 UTC, WinterSilence commented on src/generators/crud/default/controller.php
> +        $model->loadDefaultValues();
@bizley nope, we load defaults only for show form, if move up it's mixed with post data.

2021-04-06 17:24 UTC, WinterSilence commented on src/generators/crud/default/controller.php
> +        $model->loadDefaultValues();
@bizley if set `$this->searchModelClass = 'app\models\FooSearch'` by default, but in form you set property as '' (empty).

2021-04-06 17:24 UTC, bizley commented on src/generators/crud/default/controller.php
> +        $model->loadDefaultValues();
No, if we load defaults after the post fetch and there will be validation errors user should see them with the values that were there, not the default ones.

2021-04-06 17:30 UTC, WinterSilence commented on src/generators/crud/default/controller.php
> +        $model->loadDefaultValues();
@bizley you right but not in all, it's must be:
~~~php
if ($this->request->isPost) {
    if ($model->load($this->request->post()) && $model->save()) {
        return $this->redirect(['view', <?= $urlParams ?>]);
    }
} else {
   $model->loadDefaultValues();
}
~~~

2021-04-06 17:32 UTC, bizley commented on src/generators/crud/default/controller.php
> +        $model->loadDefaultValues();
It will be enough if you move it up as I said. Why you don't want to show user the default values already prefilled?

2021-04-06 17:39 UTC, WinterSilence commented on src/generators/crud/default/controller.php
> +        $model->loadDefaultValues();
@bizley  I am not sure that in this case the empty values passed from the form will not be overwritten.
> if set $this->searchModelClass = 'app\models\FooSearch' by default, but in form you set property as '' (empty).

2021-04-07 08:45 UTC, bizley commented on src/generators/crud/default/controller.php
> +        $model->loadDefaultValues();
Sending empty value overwrites the default one (as long as there is validation rule for that field so `load()` can pick it up) so it's safe to leave it like I asked to.

2021-04-09 11:59 UTC, WinterSilence commented on src/generators/crud/default/controller.php
> +        $model->loadDefaultValues();
@bizley can you explain: why my version worst than your?

2021-04-09 12:07 UTC, bizley commented on src/generators/crud/default/controller.php
> +        $model->loadDefaultValues();
Unnecessary `else`.

2021-04-09 12:26 UTC, WinterSilence commented on src/generators/crud/default/controller.php
> +        $model->loadDefaultValues();
@bizley nope, I want pass defaults only on form view and skip it on submit because it's unuseful - defaults rewrites by form data

2021-04-09 13:14 UTC, bizley commented on src/generators/crud/default/controller.php
> +        $model->loadDefaultValues();
It does not, already told you.

2021-04-09 19:19 UTC, WinterSilence commented on src/generators/crud/default/controller.php
> +        $model->loadDefaultValues();
@bizley now, `$model->loadDefaultValues();` calls only if it's **not POST** request.

2021-04-10 07:52 UTC, bizley commented on src/generators/crud/default/controller.php
> +        $model->loadDefaultValues();
Man, I don't understand you. You add PRs like #451 removing unnecessary variables but it looks like you will to fight to death for unnecessary `else` here. Sigh...

2021-04-10 10:17 UTC, merged

2021-04-10 10:17 UTC, samdark commented
Thanks!

2021-04-10 13:27 UTC, WinterSilence commented on src/generators/crud/default/controller.php
> +        $model->loadDefaultValues();
@bizley if you don't understand why it's added, then just check how it work on real model. i do it and it's work without any problems.

2021-04-10 13:34 UTC, WinterSilence commented on src/generators/crud/default/controller.php
> +        $model->loadDefaultValues();
@bizley you version work longer because call `$model->loadDefaultValues();` in any case