Add validation rules to Generator
yiisoft/yii2-gii pull request #485
Opened 2021-11-10 17:43 UTC by WinterSilence

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |

2021-11-11 13:26 UTC, samdark requested changes

2021-11-11 13:26 UTC, samdark commented on src/Generator.php
> +                'pattern' => '/^[-\w\/]+$/',
There are no such limitations on message category.

2021-11-12 16:10 UTC, WinterSilence commented on src/Generator.php
> +                'pattern' => '/^[-\w\/]+$/',
@samdark replaced to `string` validation

2021-11-18 09:33 UTC, WinterSilence commented
~~~php
$var = 1;
~~~

2021-11-18 09:39 UTC, samdark approved these changes

2021-11-18 09:39 UTC, samdark commented
Please add a CHANGELOG line.

2021-11-18 09:47 UTC, merged

2021-11-18 09:47 UTC, samdark commented
Thanks.